# Basic settings. make sure you customise site_title, site_subtitle and domain
site_title: Jilcrow
title_format: "%(site_title)s: %(title)s"
root: /
domain: "http://sjl.github.com/"
clean_urls: yes

# List tags here. Format: tag-in-url: Tag Displayed on Page
tags:
  loremipsum: Lorem Ipsum
  pirates: Pirates
  python: Python
  typography: Typography
  wikipedia: Wikipedia
  wtf: WTF

# Side bars. Answer yes or no to the ones you want/dont want
show_links_sidebar: yes
show_recent_posts: yes
show_tags_sidebar: yes

# The links that will show up in the links bar
links:
  "http://github.com/althalus/jilcrow/": Code on Github
  "http://localhost:8000/about": About
