site_title: Jilcrow
title_format: "%(site_title)s: %(title)s"
root: /
domain: "http://sjl.github.com/"
clean_urls: no

tags:
  loremipsum: Lorem Ipsum
  pirates: Pirates
  python: Python
  typography: Typography
  wikipedia: Wikipedia
  wtf: WTF
